### ISSUE TITLE
z-index too low

### ISSUE THREAD

**Issue by fabdrol** [hilongjw/vue-datepicker#6]
The z-index for the datapicker is way too low, it appears behind most of my page elements.

**Comment by veksen** [comment]
You can apply it in your own CSS. Set the required z-index on `.cov-date-body`. But yeah, maybe an option to set z-index from the JS options would be nice. Otherwise... setting a z-index in the component could be troublesome, some websites use very low z-index... 1 to 10... while some websites use evil z-index in the millions (ads are generally evil when it comes to z-index).

**Comment by bolence** [comment]
I still have problem with z-index on this component. Is there any fix for this? I tried with cov-date-body, but without luck.
